# Generated by Django 3.2.5 on 2021-08-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210808_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='github_url',
        ),
        migrations.AddField(
            model_name='project',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
